[package]
name = "rust-ingestion"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.28.1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
rusqlite = "0.27"
serde = { version = "1.0", features = ["derive"] }
